-- SQL Script para criar a tabela historico_scraping no Supabase (PostgreSQL)
-- Execute este script no painel SQL Editor do seu projeto Supabase.

CREATE TABLE IF NOT EXISTS public.historico_scraping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    silo_id TEXT NOT NULL REFERENCES public.silos(id_silo) ON DELETE CASCADE,
    data_tentativa TIMESTAMP WITH TIME ZONE NOT NULL,
    sucesso_conexao BOOLEAN DEFAULT TRUE,
    achou_dados_novos BOOLEAN DEFAULT FALSE,
    peso_kg REAL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_silo_data_tentativa UNIQUE (silo_id, data_tentativa)
);

-- Habilita RLS (Row Level Security) na tabela se desejado, ou deixa livre
ALTER TABLE public.historico_scraping ENABLE ROW LEVEL SECURITY;

-- Cria política para permitir acesso total ao service_role / API_KEY administrativo
CREATE POLICY "Permitir tudo para a role de servico" ON public.historico_scraping
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Cria política para permitir leitura pública se necessário (para o dashboard)
CREATE POLICY "Permitir leitura para anon" ON public.historico_scraping
    FOR SELECT
    TO anon
    USING (true);
